name: Weather Data Automation

on:
  schedule:
    # Run daily at 08 AM (UTC)
    - cron: '0 08 * * *'
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run Weather Script
      run: ./weather.sh

    - name: Commit and Push Changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add data/weather/*
        git commit -m "Automated weather data update"
        git push
